language: java
addons:
  sonarcloud:
    organization: davideleoni997
    token:
     secure: VF2bnnWo0g/036skRf82aWY/vI+2r+6Npn5WSievJLI4sR/NvejjN5sBnnntQDuZYeEgP8DTk0YIslutEQgeXCz7laqNCx9v65Nf//u56k5nsPv1i9q94MJHPW//qgY0FFL87ImaaNFUikuivXKKt2L17mPLTGxJB7v5hKRDkNo6CrSar0r9K8+nIOPfSfYBf3p+Vda10SY1eE7j1nPTTxiijUXS0PeeY033x/zJ8deGc4UXBoEBYNhiQkfsBJYwOJEGLNhgdItqfMDdGNEe/NXj7opuk+dfFFgW6UWh1vQxx8RyvoecFbwsb5lo3DFihd+bdhdqeZOwDjnvoUNEghOz1OD94uNPc6q1zI7HYs1ODcL4ePpI5tCGQ0ACuPNmFXq3Kb+J44OYCfCVTSn+LYmBsFSSh2RqUlMzq6NbsZ6v9EqZkzY6Co3QYcVfDsE37XQOz2x4snqPFZ0fGcs2U17qqZqWJfr5p8YnCz+hcJeToZNQ0ge0CqE0giLXXgHXPl98n2s8b9mwla5ENgTB+GQN2zO1jLHrV66OSNvGgOGjFzXo392M18JfYN9euKmWkv+C51hPOUUey4tRoLmZLJPyEkin6qbyZRKuLXzQaExvIXl6Qc3slOViXxD0xWYBomllSiYz91JiBwKuDfwS5JBeowsYX9hLt7SqaeURqIE=

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=davideleoni997_MavenTry

    